name = "bekfastclub-pack"
version = "0.69"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd0fb079284e5960aac607c2763deec64c350f4c23fc8dc4876456fa3db4f094"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
datapack-folder = "datapacks"
