name = "bekfastclub-pack"
version = "0.69"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6da271ede7f32ea1a0d4b0b229c4015c53ac85c7d2bc086fd67e221924cb9c90"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
